anwser = ""
words = []
x = input("Noun? ")
words.append(x)
x = input("Verb(third person)? ")
words.append(x)
x = input("Adjective? ")
words.append(x)
x = input("Pronoun? ")
words.append(x)
x = input("Verb (same one)? ")
words.append(x)
x = input("Adjective? ")
words.append(x)
x = input("Preposition? ")
words.append(x)
x = input("Noun? ")
words.append(x)
x = input("Verb (third person)? ")
words.append(x)
x = input("Pronoun? ")
words.append(x)
print(f"{words[0]} {words[1]} {words[2]}.  {words[3]} {words[4]} very {words[5]} {words[6]} {words[7]}. Thats what  {words[8]} {words[9]} intresting.")